In [1]:
import pandas as pd
import numpy as np
import scipy.sparse

df = pd.read_csv('500playlists.csv')

In [2]:
df = df.dropna(axis=1, inplace=False)

In [3]:
df

,missyelliott_losecontrol(feat.ciara&fatmanscoop),britneyspears_toxic,beyoncé_crazyinlove,justintimberlake_rockyourbody,shaggy_itwasn'tme,usher_yeah!,usher_myboo,thepussycatdolls_buttons,destiny'schild_saymyname,outkast_heyya!-radiomix/clubmix,...,patsycline_leavin'onyourmind-singleversion,carlenecarter_everylittlething,patsycline_thewaywardwind,keatonhenson_elevatorsong(feat.renford),keatonhenson_petrichor,spookyblack_interlude,sleepingatlast_chasingcars,tomodell_longwaydown,troyesivan_talkmedown,gnash_udon'tgetme
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,0,0,1,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,1

In [4]:
from mlxtend.frequent_patterns import apriori


freqItems = apriori(df, min_support=0.01, use_colnames=True)
freqItems['length'] = freqItems['itemsets'].apply(lambda x: len(x))

In [5]:
freqItems

      support                                           itemsets  length
0       0.010  (missyelliott_losecontrol(feat.ciara&fatmansco...       1
1       0.012                              (britneyspears_toxic)       1
2       0.032                              (beyoncé_crazyinlove)       1
3       0.012                    (justintimberlake_rockyourbody)       1
4       0.022                                (shaggy_itwasn'tme)       1
...       ...                                                ...     ...
2264    0.010  (mileycyrus_fu, lukebryan_nightone, kaleo_allt...       5
2265    0.010  (mileycyrus_fu, lukebryan_nightone, lukebryan_...       5
2266    0.010  (lukebryan_nightone, lukebryan_shegetmehigh, l...       5
2267    0.010  (mileycyrus_fu, lukebryan_nightone, lukebryan_...       5
2268    0.010  (oscarisaac_green, mileycyrus_fu, lukebryan_ni...       6

[2269 rows x 3 columns]

In [6]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(freqItems, metric="confidence", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(britneyspears_toxic),(boyslikegirls_thegreatescape),0.012,0.020,0.012,1.000000,50.000000,0.011760,inf
1,(justintimberlake_rockyourbody),(beyoncé_crazyinlove),0.012,0.032,0.010,0.833333,26.041667,0.009616,5.808
2,(solidstar_mybody),(beyoncé_crazyinlove),0.014,0.032,0.010,0.714286,22.321429,0.009552,3.388
3,(justintimberlake_rockyourbody),(usher_yeah!),0.012,0.034,0.010,0.833333,24.509804,0.009592,5.796
4,(lisaloeb&ninestories_stay),(usher_yeah!),0.010,0.034,0.010,1.000000,29.411765,0.009660,inf
...,...,...,...,...,...,...,...,...,...
1929,"(oscarisaac_green, lukebryan_suntancity)","(lukebryan_nightone, kanyewest_gorgeous, travi...",0.012,0.010,0.010,0.833333,83.333333,0.009880,5.940
1930,"(oscarisaac_green, travisatreo_youareinlove)","(lukebryan_nightone, kanyewest_gorgeous, lukeb...",0.012,0.012,0.010,0.833333,69.444444,0.009856,5.928
1931,"(lukebryan_suntancity, mileycyrus_fu)","(lukebryan_nightone, oscarisaac_green, travisa...",0.014,0.010,0.010,0.714286,71.428571,0.009860,3.465
1932,"(travisatreo_youareinlove, mileycyrus_fu)","(lukebryan_nightone, oscarisaac_green, lukebry...",0.014,0.010,0.010,0.714286,71.428571,0.009860,3.465
1933,"(lukebryan_nightone, travisatreo_youareinlove)","(oscarisaac_green, lukebryan_suntancity, kanye...",0.014,0.010,0.010,0.714286,71.428571,0.009860,3.465

In [8]:
rules.to_csv('20000Rules.csv')

In [31]:
writeRules = pd.DataFrame(rules['antecedents'].apply(lambda x: list(x)[0]).astype("unicode"))
writeRules['consequents'] = rules['consequents'].apply(lambda x: list(x)[0]).astype("unicode")

In [32]:
writeRules

                        antecedents                   consequents
0               britneyspears_toxic  boyslikegirls_thegreatescape
1     justintimberlake_rockyourbody           beyoncé_crazyinlove
2                  solidstar_mybody           beyoncé_crazyinlove
3     justintimberlake_rockyourbody                   usher_yeah!
4         lisaloeb&ninestories_stay                   usher_yeah!
...                             ...                           ...
1929               oscarisaac_green            lukebryan_nightone
1930               oscarisaac_green            lukebryan_nightone
1931           lukebryan_suntancity            lukebryan_nightone
1932       travisatreo_youareinlove            lukebryan_nightone
1933             lukebryan_nightone              oscarisaac_green

[1934 rows x 2 columns]

In [29]:
writeRules.to_csv('20000Rules.csv')

In [30]:
pd.read_csv('20000Rules.csv')

   Unnamed: 0          antecedents                   consequents
0           0  britneyspears_toxic  boyslikegirls_thegreatescape